const express = require('express')
const authController = require('../controllers/authenticationController')
const authRouter = express.Router()
authRouter.route('/signup').get(authController.signUp).post(authController.createUser)
authRouter.route('/login').get(authController.logIn).post(authController.login)
authRouter.route('/forgotPassword').post(authController.forgotPassword)
authRouter.route('/resetPassword/:token').patch(authController.resetPassword)
authRouter.route('/logOut').get(authController.logOut)
authRouter.route('/changePassword').patch(authController.protect,authController.changePassword)
authRouter.route('/protect').post(authController.protect)
module.exports = authRouter