const express = require('express')
const authController = require('../controllers/authenticationController')
const authRouter = express.Router()
authRouter.route('/signUp').get(authController.signUp).post(authController.createUser)
authRouter.route('/login').post(authController.login)
authRouter.route('/forgotPassword').post(authController.forgotPassword)
authRouter.route('/resetPassword/:token').patch(authController.resetPassword)
authRouter.route('/logIn').get(authController.logIn)
authRouter.route('/logOut').get(authController.logOut)
authRouter.route('/protect').post(authController.protect)
module.exports = authRouter